### ISSUE TITLE
Readerview won't work after upgrading readerview:  Unknown column 'rb.private' 

### ISSUE THREAD

**Issue by n-hamamoto** [gbateson/moodle-block_readerview#1]
The readerview block won't work after upgrading reader module to 2019-03-06 (03). It seems that column 'private' is removed now but remaining in the sql queries. 

---
Apr  8 15:51:53 xxxxxxxx http-error: [Mon Apr 08 15:51:53.268215 2019] [php7:notice] [pid 24508] [client 183.74.205.147:19252] Default exception handler: \x
e3\x83\x87\xe3\x83\xbc\xe3\x82\xbf\xe3\x83\x99\xe3\x83\xbc\xe3\x82\xb9\xe3\x81\xae\xe8\xaa\xad\xe3\x81\xbf\xe8\xbe\xbc\xe3\x81\xbf\xe4\xb8\xad\xe3\x81\xab
\xe3\x82\xa8\xe3\x83\xa9\xe3\x83\xbc\xe3\x81\x8c\xe7\x99\xba\xe7\x94\x9f\xe3\x81\x97\xe3\x81\xbe\xe3\x81\x97\xe3\x81\x9f\xe3\x80\x82 Debug: Unknown column
 'rb.private' in 'where clause'\nSELECT rb.id, rb.name, rb.publisher, rb.image, rb.difficulty, rb.words, rb.genre, re.evalcount, re.evaltotal, re.evalaver
age FROM mdl_reader_books rb LEFT JOIN mdl_readerview_evaluations re ON re.bookid = rb.id WHERE rb.private = 0 AND rb.hidden != 1 AND rb.genre LIKE '%%'
AND rb.fiction = 'n'    AND rb.difficulty='3'  ORDER BY rb.name ASC\n[array (\n)]\nError code: dmlreadexception\n* line 486 of /lib/dml/moodle_database.ph
p: dml_read_exception thrown\n* line 1245 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()\n* line

**Comment by gbateson** [comment]
Thank you for bringing this issue to my attention.
I have removed reference to the obsolete rb.private field in the SQL in this block.
Please could you update this plugin on your Moodle site and the next convenient opportunity and let me know if this issue is resolved.

**Comment by n-hamamoto** [comment]
Thank you very much for quick response. I have installed my moodle and confirmed that the problem is fixed.
